name: Rust CI

on:
  push:
    branches: [ main, staging]
  pull_request:
    branches: [ main, staging ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Dns_client

    steps:
    - uses: actions/checkout@v2
      with:
        path: Dns_client

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Cache Cargo registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache Cargo target
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-target-

    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin

    - name: Run tests and generate coverage report
      run: cargo tarpaulin --out Xml

    - name: Upload coverage to GitHub Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: cobertura.xml
