name: Rust

on:
  push:
    branches: [ main, staging]
  pull_request:
    branches: [ main, staging ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Install cargo-tarpaulin
      run: cargo install cargo-tarpaulin
      working-directory: Dns_client

    - name: Run tests and generate coverage report
      run: cargo tarpaulin --out Xml
      working-directory: Dns_client

    - name: Upload coverage to GitHub Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: Dns_client/cobertura.xml
    
    - name: Build
      run: cargo build --verbose
      working-directory: Dns_client

    - name: Run tests
      run: cargo test --verbose
      working-directory: Dns_client
